name: ShadowShopper
author: Sgt_Tailor
version: 1.0
main: com.shadowblox.sw123.ShadowShopping.ShadowShopping
commands:
   shadowshopping:
       usage: /shadowshopping
       description: the default ShadowShopper command