name: ShadowShopper
author: Sgt_Tailor
version: 1.0
main: com.shadowblox.sw123.ShadowShopping.ShadowShopping
commands:
    shadowshop:
        usage: /shadowshop
        description: the default ShadowShopper command